#!/usr/bin/env python3
# https://github.com/makeccx/makeccx-mini
import json, os, zipfile, glob
if not os.path.exists('dist'):
  os.mkdir('dist')
info = json.load(open('src/info.json', encoding='UTF-8'))
name = f'dist/{info['id']}@{info['version']}.ccx'
print('\n  makeccx-tiny\n  '+name+'\n')
z = zipfile.ZipFile(name, 'w', zipfile.ZIP_DEFLATED, compresslevel=9)
for i in glob.iglob('**/*', root_dir='src', recursive=True, include_hidden=True):
  i = i.replace('\\', '/')
  z.write('src/'+i, i)
